spring.application.name=online_shopping
# Khai báo đường dẫn kết nối (Nhớ thay my_database thành tên DB của bạn)
spring.datasource.url=jdbc:mysql://localhost:3306/online_shopping

# Tài khoản và mật khẩu MySQL của bạn
spring.datasource.username=root
spring.datasource.password=admin

# (Tùy chọn) Để Hibernate tự động tạo bảng dựa trên class Entity
spring.jpa.hibernate.ddl-auto=update

# (Tùy chọn) In câu lệnh SQL ra console để dễ debug
spring.jpa.show-sql=true